### ISSUE TITLE
10up SSO Button Doesn't Appear When 10up Exp Plugin Activated Per-Site

### ISSUE THREAD

**Issue by bengreeley** [10up/10up-experience#108]
### Describe the bug

When 10up Experience is installed on a multisite network and is activated per-site (not network-activated) the SSO login button doesn't appear when logging into the site. For example, if the site mysite.com is a multisite and mysite.com/site1 is a site within the multisite, the 10up SSO button doesn't appear when going to mysite.com/site1/wp-admin

Once you network-activate the 10up Experience plugin 10up SSO works as-expected.

cc @tlovett1 

### Steps to Reproduce

- Install 10up Experience on Multisite Network
- Activate plugin on individual site (not network-activate)
- Go to the wp-admin page for that site
- Observe the 10up SSO button is missing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joshuaabenazer** [comment]
@darylldoyle this doesn't seem to be an issue any longer.
