### ISSUE TITLE
Bump version for plugin update checker dependency

### ISSUE THREAD

**Issue by akshitsethi** [10up/10up-experience#118]
10up distributor requires `v4.13` of `yahnis-elsts/plugin-update-checker` while the 10up-experience plugin requires `4.8.1` and this causes dependency conflict in composer when both the plugins are used together.

https://github.com/10up/10up-experience/blob/e5ec9dc61b6259e69c5d52b862243f04648286a7/composer.json#L28

Screenshot:
<img width="1168" alt="Screenshot 2022-10-03 at 11 17 52 AM" src="https://user-images.githubusercontent.com/266324/193501269-7bbea0f4-7f84-4a76-9ec9-d883a1a62fb5.png">

**Comment by dkotter** [comment]
This should be addressed now that we've merged #116 (though note we'll need to push out an official release to take advantage of that change)
