### ISSUE TITLE
Add more common usernames

### ISSUE THREAD

**Issue by szepeviktor** [10up/10up-experience#146]
### Is your enhancement related to a problem? Please describe.

Too few "common" usernames.
https://github.com/10up/10up-experience/blob/1ef974fd5bddaa7da0ed04414d0e0ca373e4d4c3/includes/classes/Authentication/Usernames.php#L55-L68

### Designs

Mailchimp publishes a useful list.
https://mailchimp.com/help/limits-on-role-based-addresses/
Role-Based Addresses

Also viktor runs a list
https://github.com/szepeviktor/waf4wordpress/blob/5938f721e6cb23562b4f2bdae44ef57c68ea3d00/src/CoreEvents.php#L59-L95

You may copy all of them!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darylldoyle** [comment]
Thanks @szepeviktor, I'll take a look into this. I appreciate the linked resources!

**Comment by szepeviktor** [comment]
Thank you.
