### ISSUE TITLE
Plugin Compatibility: LiveBlog - Disabling Rest API breaks LiveBlog for frontend users

### ISSUE THREAD

**Issue by rickalee** [10up/10up-experience#42]
When REST API Availability is set to Restrict all access to authenticated users - Liveblog displays "There are no entries on this page." for users who are not logged in. 

I suggest we add a filter to whitelist certain routes and consider adding liveblog and oembed endpoints as defaults. 

https://github.com/10up/10up-experience/issues/38

**Comment by darylldoyle** [comment]
This is resolved in #168 via the `tenup_experience_rest_api_allowlist` filter
