### ISSUE TITLE
Remove 10up Author Pages

### ISSUE THREAD

**Issue by bengreeley** [10up/10up-experience#44]
It's common for 10up user accounts that set up a production website to be indexed on Google once the site has been launched, even if there is no content associated with those users. For example, 

https://www.wearesmartertravel.com/author/ben-greeley/
https://www.eagleview.com/author/ben-greeley/

are examples of two sites that have indexed my name. The suggested pull request, https://github.com/10up/10up-experience/pull/43 creates a 301 redirect for those pages for any users that have a @10up.com or @get10up.com e-mail address, removing them from being indexed.

**Comment by jeckman** [comment]
Do we run this plugin on 10up.com, ElasticPress.io, etc?

**Comment by tlovett1** [comment]
Not that I'm aware of @jeckman but good point. We should probably make sure the `home_url()` doesn't contain 10up.com or 10uplabs.com.

**Comment by tlovett1** [comment]
@bengreeley mind making that change?

**Comment by bengreeley** [comment]
Good points guys. I added a check for 10up domain names (10up.com, 10uplabs.com, elasticpress.io). If we have a site that needs to bypass this logic, there's a filter, `tenup_experience_allow_tenupauthor_pages` that can be set to true to allow all 10up author archives.

**Comment by bengreeley** [comment]
@jeffpaul FYI this was merged in PR #43 last year so this issue can be closed.
