### ISSUE TITLE
Deprecated error message - plugin v.1.3

### ISSUE THREAD

**Issue by eflorea** [10up/10up-experience#47]
Message:
"strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior"

Line:
"wp-content/plugins/10up-experience/vendor/plugin-update-checker/Puc/v4p4/Plugin/UpdateChecker.php:641"

**Comment by claytoncollie** [comment]
@eflorea I searched for this line of code and it doesn't exist as of 9/25/2021. This dependency has been updated since you made this ticket. Now running `v4p8`. Can you verify this issue still persists or tell me how to recreate it?

**Comment by darylldoyle** [comment]
Closing since this was a bug in the third-party plugin-update-checker library and that's long been updated.
