### ISSUE TITLE
Rewrite Rules cant be flushed when 10up Experience plugin is enabled

### ISSUE THREAD

**Issue by ivanlopez** [10up/10up-experience#51]
**Describe the bug**
If you update an existing rewrite rule or register a new post type the rewrite rules are not updating when you flush the rewrite rules. It's due to the option failsafe code. In order to flush the rules, you have to disable the plugin first.

**Steps to Reproduce**
1. Register a new public post type
2. Flush the rewrite rules
3. Create a new post and attempt to view it on the front-end
4. The content 404's because there are no rewrite rules for it

**Expected behavior**
Flushing the rewrite rules should fully regenerate the rules instead of pulling them from the cache.

**Comment by tlovett1** [comment]
@ivanlopez mind creating a PR?

**Comment by ivanlopez** [comment]
I can definitely create a PR.

**Comment by tlovett1** [comment]
Fixed in cb816671a842d6

**Comment by TheLastCicada** [comment]
Suggest closing this issue if this fix has made it into the production release?

**Comment by claytoncollie** [comment]
Can we close this issue since it was fixed in [cb81667](https://github.com/10up/10up-experience/commit/cb816671a842d6386eeb87fadc4f55862b7f6051) ? 

cc @tlovett1 @ivanlopez

**Comment by darylldoyle** [comment]
Closing since this is fixed
