### ISSUE TITLE
Option Failsafes interfering with updating Site Address (URL)

### ISSUE THREAD

**Issue by cameronterry** [10up/10up-experience#54]
**Describe the bug**
Using WordPress Core's domain mapping functionality, updating the "Site Address (URL)" on the Edit Site screen "appears" to work, however the Site becomes unusable. Upon closer inspection it is because the `home` and `siteurl` options - visible in the "Edit Site Settings" area - have not been updated.

**Steps to Reproduce**

_Please note; this was on a subfolder WordPress MultiSite and requires an additional DNS entry to be fully testable. For example; `example.test/sitetest` to `sitetest.test`. This example has been used in the following description._

1. Go to Network Admin > Sites > Add New.
2. Create a new website, `example.test/sitetest/`.
3. Go to the Edit Site screen for the new site. (The notification will give options for "Dashboard" and "Edit Site" upon successful creation.
4. On "Edit Site" screen, update the *Site Address (URL)* to be the mapped domain - `https://sitetest.test/` - and click Save Changes.
5. *Site Address (URL)* will update to the mapped domain.
6. Click on the Settings tab.
7. The *home* and *siteurl* are still with the values of `example.test/sitetest`.

If the above steps are repeated with 10up Experience deactivated, then this functionality works as expected.

**Expected behavior**
The *Site Address (URL)* and the *home* / *siteurl* should contain the same values, with the latter not including the trailing slash.

**Additional Information**
The issue seems to be with this code in the plugin;
https://github.com/10up/10up-experience/blob/cb816671a842d6386eeb87fadc4f55862b7f6051/includes/option-failsafes.php#L39-L94

And this code in WordPress Core (the issue was noticed in 4.9.12, but the same code is present in 5.3);

https://github.com/WordPress/WordPress/blob/4.9.12/wp-admin/network/site-info.php#L91-L102
https://github.com/WordPress/WordPress/blob/5.3/wp-admin/network/site-info.php#L91-L102

**Comment by tlovett1** [comment]
@christianc1 can you look at this?

**Comment by christianc1** [comment]
@tlovett1 With the second instance of this not functioning as expected, I think myself and @tott , who originally worked on this, need to review again.  I recommend pulling this feature out until such time that we can re-examine the problem and approach.

I stepped through the code and in certain circumstances, the filter on `default_option_{$option}` is causing the option to not be updated.

Addressed in https://github.com/10up/10up-experience/pull/55
