### ISSUE TITLE
1.6.x releases missing on Packagist

### ISSUE THREAD

**Issue by cameronterry** [10up/10up-experience#57]
The releases 1.6.0 and 1.6.1 are currently missing from the Packagist repository here when I was attempting to update to a specific version number; https://packagist.org/packages/10up/10up-experience.

Running the following currently notes 1.5 as the latest version.
```
composer show 10up/10up-experience --latest  
```

**Comment by jeffpaul** [comment]
@cameronterry I had thought this might get resolved by merging #56, but packagist still seems to show 1.5 as the latest version.  I wonder if we need to bump and tag a 1.6.2 to really force an update to packagist?  And yes, I tried syncing from the 10up account on packagist and that didn't seem to help.
