### ISSUE TITLE
Limit Login Default Plugin Settings

### ISSUE THREAD

**Issue by bengreeley** [10up/10up-experience#59]
**Is your enhancement related to a problem? Please describe.**
Currently the WP Limit Logins plugin https://wordpress.org/plugins/wp-limit-login-attempts/ is used on many 10up Managed Hosting sites as well as client websites. By default the plugin is set up to log all IP addresses that are blocked. Over time and after being hammered with attempted login attempts this can fill the options table and slow down queries across a site.

**Describe the solution you'd like**
Add a default option to the 10up Experience plugin to automatically disable the 'Log IP Address' option to prevent the options table from filling. If a user sets this manually, we would ignore 10up Experience from overriding the option, which could be set by a separate option set in 10up Experience.

**Comment by TheLastCicada** [comment]
If we don't log IP addresses, how would the limit logins attempt plugin know what IPs to block?

**Comment by bengreeley** [comment]
@TheLastCicada Good point, I'm not entirely sure how they handle comparison of logging. I don't really think this is a huge priority in any case, I'm going to close this issue for now.
