### ISSUE TITLE
Filtering WP List Table Views by Author Redirects to Home Page When Author Email Domain is a 10up One.

### ISSUE THREAD

**Issue by simondowdles** [10up/10up-experience#78]
**Summary of Bug**
When filtering content in any post table list view (within admin dashboard) by author, if said authors' email domain is a 10up domain, the end-user is redirected to the home page as opposed to the filtered list table. This is not the case for non-10up domain users.

**Steps to Reproduce**
1. Create a user (of a role capable of creating posts)
2. Assign an email address of domain _10up.com_ or _get10up.com_
3. Create a few posts using the said user account
4. Proceed to list table for posts, ensuring that there are some authored by said user
5. Click on the author name (ensuring it is the newly created user)
6. You will be redirected to the home page

**Expected behavior**
I expect to see the content filtered by said author, not to be redirected to the home page.

**Environment information**
 - Device: All 
 - OS: All
 - Browser and version: All
 - WordPress version: 5.5
 - Plugins and version: 1.7.3
 - Theme and version: In House Theme

**Comment by claytoncollie** [comment]
Can we close this issue now that the PR has been merged? 

cc @tlovett1 @ivanlopez

**Comment by darylldoyle** [comment]
Confirmed that this was fixed via #87, closing this issue.
