### ISSUE TITLE
Hides the WP menu link for the Stream plugin

### ISSUE THREAD

**Issue by davidegreenwald** [10up/10up-experience#88]
Activating the 10up Experience plugin hides the top left WordPress dashboard menu link for the [Stream](https://wordpress.org/plugins/stream/) user action tracking plugin. ([See screenshot](https://ps.w.org/stream/assets/screenshot-1.png?rev=2109965)) This menu item should appear between "Dashboard" and "Posts," and appears correctly once 10up Experience is deactivated. 

Tested on WordPress 5.6.4 but we have observed this across various core versions.

**Comment by helen** [comment]
Seems to be on purpose, maybe worth discussing or documenting, reference: https://github.com/10up/10up-experience/blob/e1ba86948e10da060536b0643a2476d5999dd14b/includes/classes/Plugins/Plugins.php#L70
